// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvgqbrrbmgxleuvhjogw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Z3FicnJibWd4bGV1dmhqb2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MDE5MDYsImV4cCI6MjA5MTI3NzkwNn0.ln33HFnMEuhsHyCzCotVKtWuUh8TeFmaajVjTRIEdgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});